//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-License-Identifier: Apache-2.0
// Code generated by hand (normally controller-gen). DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ─── KeckCluster ─────────────────────────────────────────────────

func (in *KeckCluster) DeepCopyInto(out *KeckCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *KeckCluster) DeepCopy() *KeckCluster {
	if in == nil { return nil }
	out := new(KeckCluster)
	in.DeepCopyInto(out)
	return out
}

func (in *KeckCluster) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}

func (in *KeckClusterList) DeepCopyInto(out *KeckClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]KeckCluster, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *KeckClusterList) DeepCopy() *KeckClusterList {
	if in == nil { return nil }
	out := new(KeckClusterList)
	in.DeepCopyInto(out)
	return out
}

func (in *KeckClusterList) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}

func (in *KeckClusterSpec) DeepCopyInto(out *KeckClusterSpec) {
	*out = *in
	in.Agent.DeepCopyInto(&out.Agent)
	in.Controller.DeepCopyInto(&out.Controller)
	out.Image = in.Image
	if in.Image.PullSecrets != nil {
		out.Image.PullSecrets = make([]corev1.LocalObjectReference, len(in.Image.PullSecrets))
		copy(out.Image.PullSecrets, in.Image.PullSecrets)
	}
}

func (in *AgentSpec) DeepCopyInto(out *AgentSpec) {
	*out = *in
	if in.NodeSelector != nil {
		out.NodeSelector = make(map[string]string, len(in.NodeSelector))
		for k, v := range in.NodeSelector {
			out.NodeSelector[k] = v
		}
	}
	if in.Tolerations != nil {
		out.Tolerations = make([]corev1.Toleration, len(in.Tolerations))
		copy(out.Tolerations, in.Tolerations)
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Redfish != nil {
		out.Redfish = new(RedfishSpec)
		*out.Redfish = *in.Redfish
	}
}

func (in *ControllerSpec) DeepCopyInto(out *ControllerSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

func (in *KeckClusterStatus) DeepCopyInto(out *KeckClusterStatus) {
	*out = *in
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}

// ─── PowerBudget ─────────────────────────────────────────────────

func (in *PowerBudget) DeepCopyInto(out *PowerBudget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *PowerBudget) DeepCopy() *PowerBudget {
	if in == nil { return nil }
	out := new(PowerBudget)
	in.DeepCopyInto(out)
	return out
}

func (in *PowerBudget) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}

func (in *PowerBudgetList) DeepCopyInto(out *PowerBudgetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]PowerBudget, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *PowerBudgetList) DeepCopy() *PowerBudgetList {
	if in == nil { return nil }
	out := new(PowerBudgetList)
	in.DeepCopyInto(out)
	return out
}

func (in *PowerBudgetList) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}

func (in *PowerBudgetStatus) DeepCopyInto(out *PowerBudgetStatus) {
	*out = *in
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
}

// ─── PowerProfile ────────────────────────────────────────────────

func (in *PowerProfile) DeepCopyInto(out *PowerProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	if in.Status.NodeNames != nil {
		out.Status.NodeNames = make([]string, len(in.Status.NodeNames))
		copy(out.Status.NodeNames, in.Status.NodeNames)
	}
}

func (in *PowerProfile) DeepCopy() *PowerProfile {
	if in == nil { return nil }
	out := new(PowerProfile)
	in.DeepCopyInto(out)
	return out
}

func (in *PowerProfile) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}

func (in *PowerProfileList) DeepCopyInto(out *PowerProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]PowerProfile, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *PowerProfileList) DeepCopy() *PowerProfileList {
	if in == nil { return nil }
	out := new(PowerProfileList)
	in.DeepCopyInto(out)
	return out
}

func (in *PowerProfileList) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}

func (in *PowerProfileSpec) DeepCopyInto(out *PowerProfileSpec) {
	*out = *in
	if in.NodeSelector != nil {
		out.NodeSelector = make(map[string]string, len(in.NodeSelector))
		for k, v := range in.NodeSelector {
			out.NodeSelector[k] = v
		}
	}
	if in.DrainIntervalMs != nil {
		out.DrainIntervalMs = new(int32)
		*out.DrainIntervalMs = *in.DrainIntervalMs
	}
	if in.GPUEnabled != nil {
		out.GPUEnabled = new(bool)
		*out.GPUEnabled = *in.GPUEnabled
	}
}

func (in *ImageSpec) DeepCopyInto(out *ImageSpec) {
	*out = *in
	if in.PullSecrets != nil {
		out.PullSecrets = make([]corev1.LocalObjectReference, len(in.PullSecrets))
		copy(out.PullSecrets, in.PullSecrets)
	}
}

func (in *RedfishSpec) DeepCopyInto(out *RedfishSpec) {
	*out = *in
	if in.NodeBMCMap != nil {
		out.NodeBMCMap = make([]NodeBMCEntry, len(in.NodeBMCMap))
		copy(out.NodeBMCMap, in.NodeBMCMap)
	}
}

func (in *NodeBMCEntry) DeepCopyInto(out *NodeBMCEntry) {
	*out = *in
}
