apiVersion: keck.io/v1alpha1
kind: KeckApplication
metadata:
  name: openshift-monitoring
spec:
  namespaces:
    - openshift-monitoring
    - openshift-user-workload-monitoring
---
apiVersion: keck.io/v1alpha1
kind: KeckApplication
metadata:
  name: openshift-networking
spec:
  namespaces:
    - openshift-ovn-kubernetes
    - openshift-multus
    - openshift-sdn
---
apiVersion: keck.io/v1alpha1
kind: KeckApplication
metadata:
  name: acm
spec:
  namespaces:
    - open-cluster-management
    - multicluster-engine
    - open-cluster-management-agent
    - open-cluster-management-agent-addon
