apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: keck-operator-catalog
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: CATALOG_IMG_PLACEHOLDER
  displayName: Keck Power Management
  publisher: Keck Project
  updateStrategy:
    registryPoll:
      interval: 10m
